<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            ['nama' => 'Alang – Alang', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Amaranthus Merah', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Amaranthus Hijau', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Ammi Majus', 'harga_beli' => 5000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Andong Hijau', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Andong Merah', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Anggrek Bulan', 'harga_beli' => 100000, 'harga_jual' => 150000, 'kategori' => 'bunga'],
            ['nama' => 'Anthurium Ecer', 'harga_beli' => 6000, 'harga_jual' => 10000, 'kategori' => 'bunga'],
            ['nama' => 'Anthurium Holland Merah', 'harga_beli' => 60000, 'harga_jual' => 85000, 'kategori' => 'bunga'],
            ['nama' => 'Anthurium Holland Putih', 'harga_beli' => 60000, 'harga_jual' => 85000, 'kategori' => 'bunga'],
            ['nama' => 'Anthurium Holland Hijau', 'harga_beli' => 60000, 'harga_jual' => 85000, 'kategori' => 'bunga'],
            ['nama' => 'Anthurium Holland Pink', 'harga_beli' => 60000, 'harga_jual' => 85000, 'kategori' => 'bunga'],
            ['nama' => 'Anthurium Lokal', 'harga_beli' => 7000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Asparagus Bintang', 'harga_beli' => 35000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Callistephus', 'harga_beli' => 25000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Cat Eye Kuning', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Rafael Kuning', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Rafael Pink', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Snoppy Pink', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Snoppy Ungu', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Ying Yang Kuning', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Mini Ying Yang Putih', 'harga_beli' => 20000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Pot', 'harga_beli' => 12000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Fanta', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Kuning Soft', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Merah', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Orange', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Pink', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Pink Soft', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Pink Salem', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Salem', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Regen / Becardi Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Remix Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Remix Merah', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Aster Remix Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Astromelia Kuning', 'harga_beli' => 25000, 'harga_jual' => 18000, 'kategori' => 'bunga'],
            ['nama' => 'Astromelia Pink', 'harga_beli' => 25000, 'harga_jual' => 18000, 'kategori' => 'bunga'],
            ['nama' => 'Astromelia Putih', 'harga_beli' => 25000, 'harga_jual' => 18000, 'kategori' => 'bunga'],
            ['nama' => 'Baby Breath', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Baby Breath Holland', 'harga_beli' => 25000, 'harga_jual' => 40000, 'kategori' => 'bunga'],
            ['nama' => 'Baby Rose Salem', 'harga_beli' => 100000, 'harga_jual' => 120000, 'kategori' => 'bunga'],
            ['nama' => 'Baby Rose Pink', 'harga_beli' => 100000, 'harga_jual' => 120000, 'kategori' => 'bunga'],
            ['nama' => 'Baby Rose Putih', 'harga_beli' => 100000, 'harga_jual' => 120000, 'kategori' => 'bunga'],
            ['nama' => 'Baby Rose Kuning', 'harga_beli' => 100000, 'harga_jual' => 120000, 'kategori' => 'bunga'],
            ['nama' => 'Bulrush', 'harga_beli' => 150000, 'harga_jual' => 200000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Merah', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Orange', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Pink', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Quenty', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calimero Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Calla Lilly Hijau', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Calla Lilly Putih', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Carnation', 'harga_beli' => 60000, 'harga_jual' => 75000, 'kategori' => 'bunga'],
            ['nama' => 'Caspea Holland', 'harga_beli' => 230000, 'harga_jual' => 350000, 'kategori' => 'bunga'],
            ['nama' => 'Cemara Angin', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Cemara Balon', 'harga_beli' => 7000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Cemara Wangi', 'harga_beli' => 8000, 'harga_jual' => 12000, 'kategori' => 'bunga'],
            ['nama' => 'Chamomile', 'harga_beli' => 300000, 'harga_jual' => 350000, 'kategori' => 'bunga'],
            ['nama' => 'Craspedia Billy Balls', 'harga_beli' => 300000, 'harga_jual' => 350000, 'kategori' => 'bunga'],
            ['nama' => 'Daun Marbel', 'harga_beli' => 13000, 'harga_jual' => 45000, 'kategori' => 'bunga'],
            ['nama' => 'Ekor Tupai', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Eucaliptus Baby Blue', 'harga_beli' => 50000, 'harga_jual' => 150000, 'kategori' => 'bunga'],
            ['nama' => 'Eucaliptus Parvi', 'harga_beli' => 40000, 'harga_jual' => 75000, 'kategori' => 'bunga'],
            ['nama' => 'Eucaliptus Silver Dollar', 'harga_beli' => 40000, 'harga_jual' => 75000, 'kategori' => 'bunga'],
            ['nama' => 'Euro Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Euro Orange', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Euro Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Florida Beauty', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Fanta', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Kuning', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Mix', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Opus White', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Pink', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Premium', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Putih', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Garbera Salem', 'harga_beli' => 18000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Dyed', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Kuning', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Lemon', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Merah', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Orange', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Pink', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Salem', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Gompie Ungu', 'harga_beli' => 16000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Heliconia Tegak', 'harga_beli' => 50000, 'harga_jual' => 75000, 'kategori' => 'bunga'],
            ['nama' => 'Heliconia Juntai', 'harga_beli' => 50000, 'harga_jual' => 75000, 'kategori' => 'bunga'],
            ['nama' => 'Hortensia Ecer', 'harga_beli' => 2500, 'harga_jual' => 5000, 'kategori' => 'bunga'],
            ['nama' => 'Hortensia Holland', 'harga_beli' => 50000, 'harga_jual' => 85000, 'kategori' => 'bunga'],
            ['nama' => 'Hortensia Lokal', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Ivy', 'harga_beli' => 7000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Jimla Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Jimla Pink', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Jimla Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Kadaka', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Karpus', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Kemuning', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Kermit Hijau', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Kermit Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Aiko Dyed', 'harga_beli' => 150000, 'harga_jual' => 175000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Aiko Putih', 'harga_beli' => 150000, 'harga_jual' => 175000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Fiji Kuning', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Fiji Merah', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Fiji Orange / Coklat', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Fiji Pink', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Fiji Putih', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Fiji Ungu', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Salju', 'harga_beli' => 15000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Sena / Jarum Kuning', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Sena / Jarum Putih', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisan Shamrock Hijau', 'harga_beli' => 15000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Krisdoren', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Leather Leaf', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Lilly Casablanca Putih', 'harga_beli' => 325000, 'harga_jual' => 400000, 'kategori' => 'bunga'],
            ['nama' => 'Lilly Casablanca Kuning', 'harga_beli' => 325000, 'harga_jual' => 400000, 'kategori' => 'bunga'],
            ['nama' => 'Lilly Casablanca Pink', 'harga_beli' => 325000, 'harga_jual' => 400000, 'kategori' => 'bunga'],
            ['nama' => 'Lilly Casablanca Merah', 'harga_beli' => 325000, 'harga_jual' => 400000, 'kategori' => 'bunga'],
            ['nama' => 'Lilly Casablanca Dyed', 'harga_beli' => 325000, 'harga_jual' => 400000, 'kategori' => 'bunga'],
            ['nama' => 'Marbel', 'harga_beli' => 13000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Marigold Orange', 'harga_beli' => 3000, 'harga_jual' => 8000, 'kategori' => 'bunga'],
            ['nama' => 'Marigold Kuning', 'harga_beli' => 3000, 'harga_jual' => 8000, 'kategori' => 'bunga'],
            ['nama' => 'Matahari Import', 'harga_beli' => 15000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Matahari Lokal', 'harga_beli' => 15000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Charming Piano', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Cherry Brandy', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Dolcetto', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Fanta PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Fanta PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Juliete', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Kuning PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Kuning PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Merah PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Merah PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Pilihan', 'harga_beli' => 50000, 'harga_jual' => 87500, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Pink PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Pink PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Putih PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Putih PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Revival PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Revival PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Salem PD', 'harga_beli' => 25000, 'harga_jual' => 60000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Salem PJ', 'harga_beli' => 25000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Sexy Red', 'harga_beli' => 25000, 'harga_jual' => 80000, 'kategori' => 'bunga'],
            ['nama' => 'Mawar Tabur', 'harga_beli' => 15000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Memusa', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Moleka', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Monstera', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Nismara Fanta', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Nismara Orange', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Nismara Pink', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Nismara Salem', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Nismara Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Pakis Sisir', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Palm', 'harga_beli' => 10000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Papyrus', 'harga_beli' => 20000, 'harga_jual' => 30000, 'kategori' => 'bunga'],
            ['nama' => 'Parvy', 'harga_beli' => 50000, 'harga_jual' => 75000, 'kategori' => 'bunga'],
            ['nama' => 'Peony Mum Putih', 'harga_beli' => 175000, 'harga_jual' => 250000, 'kategori' => 'bunga'],
            ['nama' => 'Peony Mum Dyed', 'harga_beli' => 175000, 'harga_jual' => 250000, 'kategori' => 'bunga'],
            ['nama' => 'Philodendron', 'harga_beli' => 3000, 'harga_jual' => 10000, 'kategori' => 'bunga'],
            ['nama' => 'Pikok Biru', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Pikok Pink', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Pikok Putih', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Pikok Ungu / Fanta', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Pom – Pom / Bola Kuning', 'harga_beli' => 15000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Pom – Pom / Bola Pink', 'harga_beli' => 15000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Pom – Pom / Bola Putih', 'harga_beli' => 15000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Hijau', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Mata Kebo Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Merah', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Orange', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Pink', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Lolipop', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Rados Kuning', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Rados Putih', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Puma Rados Ungu', 'harga_beli' => 14000, 'harga_jual' => 23000, 'kategori' => 'bunga'],
            ['nama' => 'Pussy Willow', 'harga_beli' => 250000, 'harga_jual' => 300000, 'kategori' => 'bunga'],
            ['nama' => 'Pytos', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Rose Lilly', 'harga_beli' => 200000, 'harga_jual' => 300000, 'kategori' => 'bunga'],
            ['nama' => 'Ruskus', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Sedap Malam', 'harga_beli' => 20000, 'harga_jual' => 35000, 'kategori' => 'bunga'],
            ['nama' => 'Sikat Botol', 'harga_beli' => 7000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Sirih Gading', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Snapdragon', 'harga_beli' => 30000, 'harga_jual' => 50000, 'kategori' => 'bunga'],
            ['nama' => 'Solidago', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Song Of India', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Song Of Jamaika', 'harga_beli' => 10000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            ['nama' => 'Tricolor', 'harga_beli' => 15000, 'harga_jual' => 25000, 'kategori' => 'bunga'],
            ['nama' => 'Tulip Holland', 'harga_beli' => 400000, 'harga_jual' => 450000, 'kategori' => 'bunga'],
            ['nama' => 'Xanado', 'harga_beli' => 10000, 'harga_jual' => 15000, 'kategori' => 'bunga'],
            ['nama' => 'Zaitun', 'harga_beli' => 15000, 'harga_jual' => 20000, 'kategori' => 'bunga'],
            
            ['nama' => 'Box', 'harga_beli' => 35000, 'harga_jual' => 35000, 'kategori' => 'packaging'],
            ['nama' => 'Wrapping', 'harga_beli' => 20000, 'harga_jual' => 20000, 'kategori' => 'packaging'],
        ];

        $products = array_map(fn ($p) => array_merge($p, [
            'created_at' => now(),
            'updated_at' => now(),
        ]), $products);

        Product::insert($products);
    }
}
