@php
    use App\Models\Product;

    $formData         = $this->data;
    $products         = $formData['products'] ?? [];
    $discountMode     = $formData['discount_mode'] ?? 'none';
    $discountModeMember = (bool) ($formData['discount_mode_member'] ?? false);
    $membershipId     = $formData['membership_id'] ?? null;
    $ongkir           = (float) ($formData['ongkir'] ?? 0);
    $boxFee           = (float) ($formData['box_fee'] ?? 0);
    $wrappingFee      = (float) ($formData['wrapping_fee'] ?? 0);
    $boxQty           = (int) ($formData['box_qty'] ?? 0);
    $wrappingQty      = (int) ($formData['wrapping_qty'] ?? 0);

    $isMember    = !empty($membershipId);

    // Konfigurasi diskon
    // Member: selalu ada diskon (dari membership atau custom per-item)
    // Non-member: hanya jika mode bukan 'none'
    $hasDiscount = $isMember || in_array($discountMode, ['global', 'per_item']);

    // Untuk keperluan label kolom
    $isPerItem = ($isMember && $discountModeMember) || (!$isMember && $discountMode === 'per_item');

    $cleanNumber = fn($val) => (float) str_replace('.', '', (string) ($val ?? 0));

    $rows             = [];
    $subtotalNormal   = 0;
    $subtotalDiscount = 0;
    $hasAnyDiscount   = false;

    foreach ($products as $item) {
        if (empty($item['product_id'])) continue;

        // cuma ambil nama produk untuk summary, harga sudah dihitung di calculateItemPrices()
        $name          = Product::whereKey($item['product_id'])->value('nama_barang') ?? '—';
        $qty           = (int) ($item['quantity'] ?? 1);
        $normalPrice   = $cleanNumber($item['normal_price']);   // unit_price * qty
        $discountPrice = $cleanNumber($item['discount_price']); // sudah dihitung di calculateItemPrices()
        $itemDiscount  = (float) ($item['item_discount'] ?? 0);

        $subtotalNormal   += $normalPrice;
        $subtotalDiscount += $discountPrice;

        // Baris ini ada diskonnya jika harga beda
        $isDiscounted = $hasDiscount && ($normalPrice !== $discountPrice);
        if ($isDiscounted) $hasAnyDiscount = true;

        $rows[] = compact('name', 'qty', 'normalPrice', 'discountPrice', 'isDiscounted', 'itemDiscount');
    }

    $totalDiskon  = $subtotalNormal - $subtotalDiscount;
    $grandTotal   = $subtotalDiscount + $ongkir + $boxFee + $wrappingFee;

    // Tampilkan baris diskon di summary hanya jika memang ada selisih
    $showDiscount = $hasAnyDiscount || ($hasDiscount && $totalDiskon > 0);
@endphp

{{-- Invoice Summary Styles Generated By AI --}}
<style>
    .inv-wrap {
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        overflow: hidden;
        font-size: 14px;
        line-height: 1.6;
    }
    .dark .inv-wrap { border-color: rgba(255,255,255,0.1); }

    /* ── Header produk ── */
    .inv-products { padding: 16px 16px 10px; }

    .inv-label {
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: #94a3b8;
        margin: 0 0 10px;
    }

    /* ── Table ── */
    .inv-tbl {
        width: 100%;
        border-collapse: collapse;
    }

    .inv-tbl th {
        font-size: 14px;
        font-weight: 600;
        color: #64748b;
        padding-bottom: 8px;
        border-bottom: 1px solid #e2e8f0;
    }
    .dark .inv-tbl th { color: #94a3b8; border-bottom-color: rgba(255,255,255,0.1); }

    .inv-tbl th.th-left  { text-align: left; }
    .inv-tbl th.th-center { text-align: center; }
    .inv-tbl th.th-right { text-align: right; }

    .inv-tbl td {
        padding: 9px 0;
        border-bottom: 1px solid #f1f5f9;
        color: #1e293b;
        vertical-align: middle;
    }
    .dark .inv-tbl td { border-bottom-color: rgba(255,255,255,0.05); color: #e2e8f0; }
    .inv-tbl tr:last-child td { border-bottom: none; }

    .td-name  { text-align: left; padding-right: 10px; }
    .td-qty   { text-align: center; padding: 0 8px; color: #64748b; white-space: nowrap; }
    .dark .td-qty { color: #94a3b8; }
    .td-price { text-align: right; }

    /* Stack harga diskon */
    .price-stack {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        gap: 1px;
    }
    .price-cross {
        font-size: 12px;
        color: #94a3b8;
        text-decoration: line-through;
    }
    .price-final {
        font-weight: 600;
        color: #1e293b;
    }
    .dark .price-final { color: #f1f5f9; }
    .price-saving {
        font-size: 11px;
        font-weight: 600;
        color: #ef4444;
    }
    .dark .price-saving { color: #f87171; }
    .price-normal {
        font-weight: 500;
        color: #1e293b;
    }
    .dark .price-normal { color: #f1f5f9; }

    /* ── Summary footer ── */
    .inv-summary {
        border-top: 1px solid #e2e8f0;
        background: #f8fafc;
        padding: 12px 16px;
    }
    .dark .inv-summary {
        border-top-color: rgba(255,255,255,0.1);
        background: rgba(255,255,255,0.03);
    }

    .inv-stbl { width: 100%; border-collapse: collapse; }
    .inv-stbl td { padding: 4px 0; font-size: 14px; }
    .inv-stbl td:last-child { text-align: right; }

    .s-muted  { color: #64748b; }
    .dark .s-muted { color: #94a3b8; }
    .s-strike { color: #94a3b8; text-decoration: line-through; }
    .s-disc   { color: #ef4444; font-weight: 600; }
    .dark .s-disc { color: #f87171; }
    .s-normal { color: #334155; }
    .dark .s-normal { color: #cbd5e1; }

    .inv-stbl tr.grand-row td {
        padding-top: 10px;
        border-top: 1px solid #e2e8f0;
        font-weight: 700;
        font-size: 14px;
        color: #0f172a;
    }
    .dark .inv-stbl tr.grand-row td {
        border-top-color: rgba(255,255,255,0.1);
        color: #f8fafc;
    }
    .grand-amount {
        color: #2563eb;
        font-weight: 700;
        text-align: right;
    }
    .dark .grand-amount { color: #60a5fa; }

    /* ── Empty state ── */
    .inv-empty {
        border: 2px dashed #cbd5e1;
        border-radius: 12px;
        padding: 32px 16px;
        text-align: center;
        font-size: 13px;
        color: #94a3b8;
    }
    .dark .inv-empty { border-color: #475569; color: #64748b; }

    /* ── Responsive: layar kecil (<520px) ── */
    @media (max-width: 520px) {
        .inv-wrap { font-size: 13px; border-radius: 10px; }
        .inv-products { padding: 12px 12px 8px; }
        .inv-summary { padding: 10px 12px; }

        .inv-tbl th { font-size: 12px; padding-bottom: 6px; }
        .inv-tbl td { padding: 7px 0; font-size: 13px; }
        .inv-stbl td { font-size: 12px; padding: 3px 0; }

        .inv-stbl tr.grand-row td { font-size: 13px; padding-top: 8px; }

        /* Kolom nama lebih longgar di HP */
        .td-name  { padding-right: 6px; }
        .td-qty   { padding: 0 5px; }

        .price-cross  { font-size: 11px; }
        .price-saving { font-size: 10px; }
    }
</style>

@if (empty($rows))
    <div class="inv-empty">
        Belum ada produk yang ditambahkan.
    </div>
@else
    <div class="inv-wrap">

        {{-- ── Daftar Produk ── --}}
        <div class="inv-products">
            <p class="inv-label">Daftar Produk</p>
            <table class="inv-tbl">
                <thead>
                    <tr>
                        <th class="th-left">Produk</th>
                        <th class="th-center">Qty</th>
                        <th class="th-right">Harga</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($rows as $row)
                        <tr>
                            <td class="td-name">{{ $row['name'] }}</td>
                            <td class="td-qty">{{ $row['qty'] }}</td>
                            <td class="td-price">
                                @if ($row['isDiscounted'])
                                    <div class="price-stack">
                                        <span class="price-cross">
                                            Rp {{ number_format($row['normalPrice'], 0, ',', '.') }}
                                        </span>
                                        <span class="price-final">
                                            Rp {{ number_format($row['discountPrice'], 0, ',', '.') }}
                                        </span>
                                        <span class="price-saving">
                                            -Rp {{ number_format($row['normalPrice'] - $row['discountPrice'], 0, ',', '.') }}
                                        </span>
                                    </div>
                                @else
                                    <span class="price-normal">
                                        Rp {{ number_format($row['normalPrice'], 0, ',', '.') }}
                                    </span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        {{-- ── Summary ── --}}
        <div class="inv-summary">
            <table class="inv-stbl">
                <tbody>

                    {{-- Subtotal dengan/tanpa diskon --}}
                    @if ($showDiscount)
                        <tr>
                            <td class="s-muted">Subtotal (sebelum diskon)</td>
                            <td class="s-strike">Rp {{ number_format($subtotalNormal, 0, ',', '.') }}</td>
                        </tr>
                        <tr>
                            <td class="s-disc">Total Diskon</td>
                            <td class="s-disc">- Rp {{ number_format($totalDiskon, 0, ',', '.') }}</td>
                        </tr>
                        <tr>
                            <td class="s-normal">Subtotal (setelah diskon)</td>
                            <td class="s-normal">Rp {{ number_format($subtotalDiscount, 0, ',', '.') }}</td>
                        </tr>
                    @else
                        <tr>
                            <td class="s-muted">Subtotal</td>
                            <td class="s-normal">Rp {{ number_format($subtotalDiscount, 0, ',', '.') }}</td>
                        </tr>
                    @endif

                    {{-- Ongkir — selalu tampil agar user sadar nilainya --}}
                    <tr>
                        <td class="s-muted">Ongkos Kirim</td>
                        <td class="s-normal">
                            @if ($ongkir > 0)
                                Rp {{ number_format($ongkir, 0, ',', '.') }}
                            @else
                                <span style="color:#ef4444;font-weight:500;">Rp 0 ⚠️</span>
                            @endif
                        </td>
                    </tr>

                    {{-- Box — hanya tampil jika diaktifkan --}}
                    @if ($boxFee > 0)
                        <tr>
                            <td class="s-muted">
                                Box
                                @if ($boxQty > 1)
                                    <span style="font-size:11px;color:#94a3b8;">({{ $boxQty }} pcs)</span>
                                @endif
                            </td>
                            <td class="s-normal">Rp {{ number_format($boxFee, 0, ',', '.') }}</td>
                        </tr>
                    @endif

                    {{-- Wrapping — hanya tampil jika diaktifkan --}}
                    @if ($wrappingFee > 0)
                        <tr>
                            <td class="s-muted">
                                Wrapping
                                @if ($wrappingQty > 1)
                                    <span style="font-size:11px;color:#94a3b8;">({{ $wrappingQty }} pcs)</span>
                                @endif
                            </td>
                            <td class="s-normal">Rp {{ number_format($wrappingFee, 0, ',', '.') }}</td>
                        </tr>
                    @endif

                    {{-- Grand Total --}}
                    <tr class="grand-row">
                        <td>Grand Total</td>
                        <td class="grand-amount">Rp {{ number_format($grandTotal, 0, ',', '.') }}</td>
                    </tr>

                </tbody>
            </table>
        </div>

    </div>
@endif