<?php

namespace App\Policies;

use App\Models\GeneralJournal;
use App\Models\User;

class GeneralJournalPolicy
{
    public function viewAny(User $user): bool
    {
        return $user->is_super_admin;
    }

    public function view(User $user, GeneralJournal $generalJournal): bool
    {
        return $user->is_super_admin;
    }

    public function create(User $user): bool
    {
        return $user->is_super_admin;
    }

    /**
     * Only allow editing manual journals (reference_id is null).
     */
    public function update(User $user, GeneralJournal $generalJournal): bool
    {
        return $user->is_super_admin && !$generalJournal->isAutoGenerated();
    }

    /**
     * Only allow deleting manual journals (reference_id is null).
     */
    public function delete(User $user, GeneralJournal $generalJournal): bool
    {
        return $user->is_super_admin && !$generalJournal->isAutoGenerated();
    }

    public function deleteAny(User $user): bool
    {
        return $user->is_super_admin;
    }
}
