<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class GeneralJournal extends Model
{
    protected $table = 'bl_general_journals_t';

    protected $fillable = [
        'tanggal',
        'no_bukti',
        'keterangan',
        'reference_id',
        'source_type',
    ];

    protected $casts = [
        'tanggal' => 'date',
    ];

    /**
     * Journal detail items (debit/kredit lines).
     */
    public function items(): HasMany
    {
        return $this->hasMany(JournalItem::class, 'journal_id');
    }

    /**
     * Whether this journal was auto-generated by the system.
     */
    public function isAutoGenerated(): bool
    {
        return $this->reference_id !== null;
    }

    /**
     * Guard: block creating/updating/deleting if period is closed or doesn't exist.
     */
    protected static function booted(): void
    {
        static::updated(function (GeneralJournal $journal) {
            app(\App\Services\AccountingAuditService::class)->record(
                'updated',
                $journal,
                $journal->getOriginal(),
                $journal->getChanges(),
            );
        });

        static::deleted(function (GeneralJournal $journal) {
            app(\App\Services\AccountingAuditService::class)->record(
                'deleted',
                $journal,
                $journal->getOriginal(),
                null,
            );
        });

        static::saving(function (GeneralJournal $journal) {
            if (!$journal->tanggal) {
                $journal->tanggal = now()->toDateString();
            }

            $period = \App\Models\AccountingPeriod::where('start_date', '<=', $journal->tanggal)
                ->where('end_date', '>=', $journal->tanggal)
                ->first();

            if (!$period) {
                throw new \RuntimeException("Tanggal jurnal ({$journal->tanggal->format('Y-m-d')}) tidak masuk ke dalam Periode Akuntansi manapun.");
            }

            if ($period->isClosed()) {
                throw new \RuntimeException("Periode akuntansi '{$period->label}' sudah ditutup. Jurnal tidak bisa disimpan.");
            }
        });

        static::deleting(function (GeneralJournal $journal) {
            $period = \App\Models\AccountingPeriod::where('start_date', '<=', $journal->tanggal)
                ->where('end_date', '>=', $journal->tanggal)
                ->first();

            if ($period && $period->isClosed()) {
                throw new \RuntimeException("Periode akuntansi '{$period->label}' sudah ditutup. Jurnal tidak bisa dihapus.");
            }
        });
    }
}
