<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class GeneralJournal extends Model
{
    protected $table = 'bl_general_journals_t';

    protected $fillable = [
        'no_bukti',
        'keterangan',
        'reference_id',
        'source_type',
    ];

    /**
     * Journal detail items (debit/kredit lines).
     */
    public function items(): HasMany
    {
        return $this->hasMany(JournalItem::class, 'journal_id');
    }

    /**
     * Whether this journal was auto-generated by the system.
     */
    public function isAutoGenerated(): bool
    {
        return $this->reference_id !== null;
    }
}
